# Generated by Django 3.0.8 on 2020-07-15 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('application_date', models.DateTimeField(default=datetime.datetime(2020, 7, 15, 15, 40, 48, 364491, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('period', models.CharField(help_text='e.g (1 month, 6 months, 1 year)', max_length=18)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('offer_date', models.DateTimeField(default=datetime.datetime(2020, 7, 15, 15, 40, 48, 357940, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='OfferReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('review', models.IntegerField(help_text="Select review from 1 to 10. '1' is the smallest one.")),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('review', models.IntegerField(help_text="Select review from 1 to 10. '1' is the smallest one.")),
            ],
        ),
    ]
