# Generated by Django 3.0.8 on 2020-07-17 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20200717_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 26, 20, 382147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 26, 20, 380854, tzinfo=utc)),
        ),
    ]
