# Generated by Django 3.0.8 on 2020-07-17 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, help_text='attach some files', null=True, upload_to='')),
                ('message_date', models.DateTimeField(default=datetime.datetime(2020, 7, 17, 11, 23, 0, 547005, tzinfo=utc))),
            ],
        ),
    ]
